apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-monitoring
  namespace: portfolio
  labels:
    release: prometheus 
spec:
  selector:
    matchLabels:
      app: nginx-metrics
  endpoints:
    - interval: 5s
      path: /metrics 
      port: metrics
  namespaceSelector:
    matchNames:
      - "portfolio"
