apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sockshop
  namespace: sock-shop
spec:
  ingressClassName: nginx
  rules:
      -  host: sockshop.fiiyinfoluwa.live
         http:
          paths:
          - backend:
              service:
                name: front-end
                port:
                  number: 80
            path: /
            pathType: Prefix
